<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>cloud.charging.open.protocols.EEBUS.CLI</RootNamespace>
    <AssemblyName>eebus</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EEBUSSimulations\EEBUSSimulations.csproj" />
    <ProjectReference Include="..\..\EEBUSConformance\EEBUSConformance.csproj" />
  </ItemGroup>

</Project>
