/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of EEBUSConformanceTests <https://github.com/OpenChargingCloud/EEBUSConformanceTests>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Text;
using System.Text.RegularExpressions;

#endregion

namespace cloud.charging.open.protocols.EEBUS.ModelGen
{

    /// <summary>
    /// Writes the C# files of the SPINE data model.
    /// </summary>
    /// <param name="Model">The model read from the XSDs.</param>
    /// <param name="OutputDirectory">The directory below which the model is written.</param>
    public sealed class Emitter(SpineModel  Model,
                                String      OutputDirectory)
    {

        #region Data

        private const String Namespace = "cloud.charging.open.protocols.EEBUS.SPINE.Model";

        /// <summary>
        /// The framework types used by the generated string types, and where
        /// they live. Only these are written out in full when a value of the
        /// specification is called like one of them - a value called "value"
        /// shadows nothing, it just happens to look like a parameter name.
        /// </summary>
        private static readonly (String Type, String Namespace)[] frameworkTypes = [
            ( "Boolean",           "System"                    ),
            ( "String",            "System"                    ),
            ( "Int32",             "System"                    ),
            ( "Int64",             "System"                    ),
            ( "UInt32",            "System"                    ),
            ( "UInt64",            "System"                    ),
            ( "Object",            "System"                    ),
            ( "StringComparer",    "System"                    ),
            ( "StringComparison",  "System"                    ),
            ( "ArgumentException", "System"                    ),
            ( "IEquatable",        "System"                    ),
            ( "IComparable",       "System"                    ),
            ( "Dictionary",        "System.Collections.Generic" ),
            ( "IEnumerable",       "System.Collections.Generic" )
        ];

        private readonly List<String> writtenFiles = [];

        #endregion

        #region Properties

        /// <summary>
        /// The files written by the last run.
        /// </summary>
        public IEnumerable<String> WrittenFiles
            => writtenFiles;

        #endregion


        #region Emit()

        /// <summary>
        /// Write the whole model.
        /// </summary>
        public void Emit()
        {

            writtenFiles.Clear();

            Directory.CreateDirectory(OutputDirectory);
            Directory.CreateDirectory(Path.Combine(OutputDirectory, "PredefinedStrings"));

            // Only the C# files are removed, and only those which say that they
            // were generated: a type which disappears from the XSDs has to
            // disappear from the model as well, but the output directory is not
            // ours to empty.
            foreach (var file in Directory.GetFiles(OutputDirectory, "*.cs", SearchOption.AllDirectories))
                if (File.ReadLines(file).Take(30).Any(line => line.Contains("<auto-generated>", StringComparison.Ordinal)))
                    File.Delete(file);

            foreach (var resource in Model.Classes.
                                         GroupBy(complexType => complexType.Resource, StringComparer.Ordinal).
                                         OrderBy(group       => group.Key,            StringComparer.Ordinal))
            {
                EmitClasses(resource.Key, [.. resource]);
            }

            foreach (var stringType in Model.StringTypes)
                EmitStringType(stringType);

            EmitFunctionRegistry();

        }

        #endregion


        #region (private) EmitClasses(Resource, Classes)

        private void EmitClasses(String Resource, List<SpineClass> Classes)
        {

            var builder = Header(
                              $"the complex types of EEBus_SPINE_TS_{Resource}.xsd",
                              [ "Newtonsoft.Json" ]
                          );

            foreach (var complexType in Classes.OrderBy(entry => entry.Name, StringComparer.Ordinal))
            {

                builder.AppendLine();
                builder.AppendLine( "    /// <summary>");
                builder.AppendLine($"    /// {complexType.Name} (SPINE {Model.Version}, EEBus_SPINE_TS_{Resource}.xsd).");
                builder.AppendLine( "    /// </summary>");
                // OptIn, so that only the properties declared here go over the
                // wire. Everything the XSD cannot say - what a scaled number is
                // worth, how an address reads, which function a command carries -
                // is written next to this file as a partial class under
                // WWCP_EEBUS_SPINE/Additions/, and none of it may end up in a
                // datagram by accident.
                builder.AppendLine( "    [JsonObject(MemberSerialization.OptIn)]");
                builder.AppendLine($"    public partial class {complexType.Name}");
                builder.AppendLine( "    {");

                var order = 0;

                foreach (var property in complexType.Properties)
                {

                    order++;

                    var type = property.IsList
                                   ? $"List<{property.CSharpType}>?"
                                   : $"{property.CSharpType}?";

                    builder.AppendLine();
                    builder.AppendLine( "        /// <summary>");
                    builder.AppendLine($"        /// {Naming.XmlEscape(property.XmlName)}");
                    builder.AppendLine( "        /// </summary>");

                    if (property.IsKey)
                        builder.AppendLine(property.IsPrimaryKey
                                               ? "        [EEBUSKey(IsPrimary: true)]"
                                               : "        [EEBUSKey]");

                    if (property.IsWriteCheck)
                        builder.AppendLine("        [EEBUSWriteCheck]");

                    if (property.Function is not null && property.Part != FunctionPart.None)
                        builder.AppendLine($"        [EEBUSFunction(\"{property.Function}\", EEBUSFunctionPart.{property.Part})]");

                    // The order is written down rather than left to the order of
                    // the declarations: EEBUS JSON is an ordered format, and a
                    // reordering while refactoring must not change a datagram.
                    builder.AppendLine($"        [JsonProperty(\"{property.XmlName}\", NullValueHandling = NullValueHandling.Ignore, Order = {order})]");
                    builder.AppendLine($"        public {type} {property.CSharpName} {{ get; set; }}");

                }

                builder.AppendLine();
                builder.AppendLine("    }");
                builder.AppendLine();

            }

            builder.AppendLine("}");

            Write(Path.Combine(OutputDirectory, $"{Resource}.cs"), builder);

        }

        #endregion

        #region (private) EmitStringType(StringType)

        private void EmitStringType(SpineStringType StringType)
        {

            var name       = StringType.Name;
            var valueNames = Naming.ValueNames(StringType.Values);

            // A value of the specification may be called like a type of the
            // framework: "DeviceConfigurationKeyValueTypeType" has the values
            // "boolean" and "string". Within the struct the property wins over
            // the type, so every type it shadows is written out in full - and
            // the value names themselves are protected from that rewriting.
            var shadowed   = valueNames.Values.ToHashSet(StringComparer.Ordinal);
            var protects   = new List<String>();

            String Protect(String Text)
            {
                protects.Add(Text);
                return $"{protects.Count - 1}";
            }

            var builder    = Header(
                                 $"{name}, from EEBus_SPINE_TS_{StringType.Resource}.xsd",
                                 [ "Newtonsoft.Json", "org.GraphDefined.Vanaheimr.Illias" ]
                             );

            #region The extension methods

            builder.AppendLine();
            builder.AppendLine( "    /// <summary>");
            builder.AppendLine($"    /// Extension methods for {name}.");
            builder.AppendLine( "    /// </summary>");
            builder.AppendLine($"    public static class {name}Extensions");
            builder.AppendLine( "    {");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Indicates whether this {name} is null or empty.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine($"        /// <param name=\"Value\">A {name}.</param>");
            builder.AppendLine($"        public static Boolean IsNullOrEmpty(this {name}? Value)");
            builder.AppendLine( "            => !Value.HasValue || Value.Value.IsNullOrEmpty;");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Indicates whether this {name} is NOT null or empty.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine($"        /// <param name=\"Value\">A {name}.</param>");
            builder.AppendLine($"        public static Boolean IsNotNullOrEmpty(this {name}? Value)");
            builder.AppendLine( "            => Value.HasValue && Value.Value.IsNotNullOrEmpty;");
            builder.AppendLine();
            builder.AppendLine( "    }");
            builder.AppendLine();

            #endregion

            #region The type itself

            builder.AppendLine();
            builder.AppendLine( "    /// <summary>");
            builder.AppendLine($"    /// {name} (SPINE {Model.Version}, EEBus_SPINE_TS_{StringType.Resource}.xsd).");
            builder.AppendLine( "    ///");

            builder.AppendLine(StringType.IsExtensible
                                   ? $"    /// The specification defines {StringType.Values.Count} value(s) and unions them with \"EnumExtendType\","
                                   : $"    /// The specification defines {StringType.Values.Count} value(s).");

            builder.AppendLine(StringType.IsExtensible
                                   ? "    /// so a value of a manufacturer is a legal value here."
                                   : "    /// It is not an extensible enumeration.");

            builder.AppendLine( "    ///");
            builder.AppendLine( "    /// Parsing is tolerant either way: a value which the specification does not");
            builder.AppendLine( "    /// define has to survive being received, so that it can be reported. Whether");
            builder.AppendLine( "    /// it is allowed here is decided by the conformance tests, see IsDefined.");
            builder.AppendLine( "    /// </summary>");
            builder.AppendLine($"    [JsonConverter(typeof(SPINEStringTypeConverter<{name}>))]");
            builder.AppendLine($"    public readonly struct {name} : IId,");
            builder.AppendLine($"                                    ISPINEStringType<{name}>,");
            builder.AppendLine($"                                    IEquatable<{name}>,");
            builder.AppendLine($"                                    IComparable<{name}>");
            builder.AppendLine( "    {");
            builder.AppendLine();

            #region Data

            builder.AppendLine( "        #region Data");
            builder.AppendLine();
            builder.AppendLine( "        // Ordinal, not OrdinalIgnoreCase: the values of SPINE are case sensitive.");
            builder.AppendLine( "        // The units of measurement contain both \"s\" (second) and \"S\" (siemens).");
            builder.AppendLine($"        private readonly static Dictionary<String, {name}>  lookup = new (StringComparer.Ordinal);");
            builder.AppendLine( "        private readonly        String                      InternalId;");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();

            #endregion

            #region Properties

            builder.AppendLine( "        #region Properties");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Indicates whether this value is null or empty.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public readonly  Boolean  IsNullOrEmpty");
            builder.AppendLine( "            => InternalId.IsNullOrEmpty();");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Indicates whether this value is NOT null or empty.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public readonly  Boolean  IsNotNullOrEmpty");
            builder.AppendLine( "            => InternalId.IsNotNullOrEmpty();");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// The length of the value.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public readonly  UInt64   Length");
            builder.AppendLine( "            => (UInt64) (InternalId?.Length ?? 0);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();

            #endregion

            #region Constructor, Register, Parse, TryParse

            builder.AppendLine( "        #region Constructor(s)");
            builder.AppendLine();
            builder.AppendLine($"        private {name}(String Text)");
            builder.AppendLine( "        {");
            builder.AppendLine( "            this.InternalId = Text;");
            builder.AppendLine( "        }");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine( "        #region (private static) Register(Text)");
            builder.AppendLine();
            builder.AppendLine($"        private static {name} Register(String Text)");
            builder.AppendLine();
            builder.AppendLine( "            => lookup.AddAndReturnValue(");
            builder.AppendLine( "                   Text,");
            builder.AppendLine($"                   new {name}(Text)");
            builder.AppendLine( "               );");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine( "        #region (static) Parse   (Text)");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Parse the given text as a {name}.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Text\">A text representation.</param>");
            builder.AppendLine($"        public static {name} Parse(String Text)");
            builder.AppendLine( "        {");
            builder.AppendLine();
            builder.AppendLine( "            if (TryParse(Text, out var value))");
            builder.AppendLine( "                return value;");
            builder.AppendLine();
            builder.AppendLine($"            throw new ArgumentException(\"The given text representation of a {name} is invalid!\",");
            builder.AppendLine( "                                        nameof(Text));");
            builder.AppendLine();
            builder.AppendLine( "        }");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region (static) TryParse(Text)");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Try to parse the given text as a {name}.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Text\">A text representation.</param>");
            builder.AppendLine($"        public static {name}? TryParse(String Text)");
            builder.AppendLine( "        {");
            builder.AppendLine();
            builder.AppendLine( "            if (TryParse(Text, out var value))");
            builder.AppendLine( "                return value;");
            builder.AppendLine();
            builder.AppendLine( "            return null;");
            builder.AppendLine();
            builder.AppendLine( "        }");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region (static) TryParse(Text, out Value)");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Try to parse the given text as a {name}.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Text\">A text representation.</param>");
            builder.AppendLine( "        /// <param name=\"Value\">The parsed value.</param>");
            builder.AppendLine($"        public static Boolean TryParse(String Text, out {name} Value)");
            builder.AppendLine( "        {");
            builder.AppendLine();
            builder.AppendLine( "            Text = Text.Trim();");
            builder.AppendLine();
            builder.AppendLine( "            if (Text.IsNotNullOrEmpty())");
            builder.AppendLine( "            {");
            builder.AppendLine();
            builder.AppendLine( "                if (!lookup.TryGetValue(Text, out Value))");
            builder.AppendLine( "                    Value = Register(Text);");
            builder.AppendLine();
            builder.AppendLine( "                return true;");
            builder.AppendLine();
            builder.AppendLine( "            }");
            builder.AppendLine();
            builder.AppendLine( "            Value = default;");
            builder.AppendLine( "            return false;");
            builder.AppendLine();
            builder.AppendLine( "        }");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();

            #endregion

            #region The values of the specification

            builder.AppendLine();
            builder.AppendLine( "        #region Static definitions");
            builder.AppendLine();

            foreach (var value in StringType.Values)
            {
                builder.AppendLine( "        /// <summary>");
                builder.AppendLine($"        /// {Naming.XmlEscape(value)}");
                builder.AppendLine( "        /// </summary>");
                builder.AppendLine($"        public static {name}  {Protect(valueNames[value])}   {{ get; }}");
                builder.AppendLine($"            = Register(\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\");");
                builder.AppendLine();
            }

            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region Validity");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// All values defined by SPINE {Model.Version}.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine($"        public static IEnumerable<{name}>  All    {{ get; }}");

            if (StringType.Values.Count == 0)
                builder.AppendLine("            = [];");

            else
            {

                builder.AppendLine("            = [");

                for (var i = 0; i < StringType.Values.Count; i++)
                    builder.AppendLine($"                  {Protect(valueNames[StringType.Values[i]])}{(i < StringType.Values.Count - 1 ? "," : "")}");

                builder.AppendLine("              ];");

            }

            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine($"        /// Whether this is one of the values defined by SPINE {Model.Version}.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public Boolean IsDefined");
            builder.AppendLine( "            => All.Contains(this);");
            builder.AppendLine();
            builder.AppendLine($"        /// <summary>");
            builder.AppendLine($"        /// Whether this enumeration may carry values which the specification does not define.");
            builder.AppendLine($"        /// </summary>");
            builder.AppendLine($"        public static Boolean IsExtensible    {{ get; }}");
            builder.AppendLine($"            = {(StringType.IsExtensible ? "true" : "false")};");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();

            #endregion

            #region Operators, equality, comparison, ToString

            builder.AppendLine();
            builder.AppendLine( "        #region Operator overloading");
            builder.AppendLine();

            foreach (var (op, expression) in new (String, String)[] {
                         ( "==", "Value1.Equals(Value2)"          ),
                         ( "!=", "!Value1.Equals(Value2)"         ),
                         ( "<",  "Value1.CompareTo(Value2) <  0"  ),
                         ( "<=", "Value1.CompareTo(Value2) <= 0"  ),
                         ( ">",  "Value1.CompareTo(Value2) >  0"  ),
                         ( ">=", "Value1.CompareTo(Value2) >= 0"  )
                     })
            {
                builder.AppendLine( "        /// <summary>");
                builder.AppendLine( "        /// Compares two values.");
                builder.AppendLine( "        /// </summary>");
                builder.AppendLine($"        public static Boolean operator {op} ({name} Value1, {name} Value2)");
                builder.AppendLine($"            => {expression};");
                builder.AppendLine();
            }

            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine($"        #region IComparable<{name}> Members");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Compares two values.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Object\">A value to compare with.</param>");
            builder.AppendLine( "        public Int32 CompareTo(Object? Object)");
            builder.AppendLine();
            builder.AppendLine($"            => Object is {name} value");
            builder.AppendLine( "                   ? CompareTo(value)");
            builder.AppendLine($"                   : throw new ArgumentException(\"The given object is not a {name}!\",");
            builder.AppendLine( "                                                 nameof(Object));");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Compares two values.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Value\">A value to compare with.</param>");
            builder.AppendLine($"        public Int32 CompareTo({name} Value)");
            builder.AppendLine();
            builder.AppendLine( "            => String.Compare(InternalId,");
            builder.AppendLine( "                              Value.InternalId,");
            builder.AppendLine( "                              StringComparison.Ordinal);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine($"        #region IEquatable<{name}> Members");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Compares two values for equality.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Object\">A value to compare with.</param>");
            builder.AppendLine( "        public override Boolean Equals(Object? Object)");
            builder.AppendLine();
            builder.AppendLine($"            => Object is {name} value &&");
            builder.AppendLine( "                   Equals(value);");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Compares two values for equality.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Value\">A value to compare with.</param>");
            builder.AppendLine($"        public Boolean Equals({name} Value)");
            builder.AppendLine();
            builder.AppendLine( "            => String.Equals(InternalId,");
            builder.AppendLine( "                             Value.InternalId,");
            builder.AppendLine( "                             StringComparison.Ordinal);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region (override) GetHashCode()");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Return the hash code of this object.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public override Int32 GetHashCode()");
            builder.AppendLine();
            builder.AppendLine( "            => InternalId?.GetHashCode() ?? 0;");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region (override) ToString()");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Return the text representation of this value.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public override String ToString()");
            builder.AppendLine();
            builder.AppendLine( "            => InternalId ?? \"\";");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "    }");
            builder.AppendLine();
            builder.AppendLine( "}");

            #endregion

            #endregion

            Write(Path.Combine(OutputDirectory, "PredefinedStrings", $"{name}.cs"),
                  Qualify(builder.ToString(), shadowed, protects));

        }

        #endregion

        #region (private static) Qualify(Text, Shadowed, Protects)

        /// <summary>
        /// Write out in full every framework type which a value of the
        /// specification shadows, and put the protected value names back.
        /// </summary>
        private static String Qualify(String        Text,
                                      HashSet<String>  Shadowed,
                                      List<String>     Protects)
        {

            foreach (var (type, @namespace) in frameworkTypes)
            {

                if (!Shadowed.Contains(type))
                    continue;

                Text = Regex.Replace(Text,
                                     $@"\b{Regex.Escape(type)}\b",
                                     $"{@namespace}.{type}");

            }

            for (var i = 0; i < Protects.Count; i++)
                Text = Text.Replace($"{i}", Protects[i], StringComparison.Ordinal);

            return Text;

        }

        #endregion

        #region (private) EmitFunctionRegistry()

        private void EmitFunctionRegistry()
        {

            var builder = Header(
                              "the registry of all SPINE functions",
                              []
                          );

            builder.AppendLine();
            builder.AppendLine( "    /// <summary>");
            builder.AppendLine( "    /// One function of the SPINE data model, together with the three types");
            builder.AppendLine( "    /// which represent it within a command frame.");
            builder.AppendLine( "    /// </summary>");
            builder.AppendLine( "    /// <param name=\"Name\">The function name, as within \"FunctionEnumType\".</param>");
            builder.AppendLine( "    /// <param name=\"Resource\">The resource (XSD) the function belongs to.</param>");
            builder.AppendLine( "    /// <param name=\"DataType\">The type of the function data.</param>");
            builder.AppendLine( "    /// <param name=\"SelectorsType\">The type of its selectors, where it has any.</param>");
            builder.AppendLine( "    /// <param name=\"ElementsType\">The type of its elements, where it has any.</param>");
            builder.AppendLine( "    public sealed record SPINEFunctionInfo(String  Name,");
            builder.AppendLine( "                                          String  Resource,");
            builder.AppendLine( "                                          Type    DataType,");
            builder.AppendLine( "                                          Type?   SelectorsType,");
            builder.AppendLine( "                                          Type?   ElementsType);");
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine( "    /// <summary>");
            builder.AppendLine($"    /// All {Model.Functions.Count} functions of SPINE {Model.Version}.");
            builder.AppendLine( "    ///");
            builder.AppendLine( "    /// This is the mechanical counterpart of the three choice groups of the");
            builder.AppendLine( "    /// command frame: which functions exist is not a matter of opinion, it is");
            builder.AppendLine( "    /// what \"DataChoiceGroup\", \"DataSelectorsChoiceGroup\" and");
            builder.AppendLine( "    /// \"DataElementsChoiceGroup\" say.");
            builder.AppendLine( "    /// </summary>");
            builder.AppendLine( "    public static class SPINEFunctions");
            builder.AppendLine( "    {");
            builder.AppendLine();
            builder.AppendLine( "        #region Data");
            builder.AppendLine();
            builder.AppendLine( "        private static readonly SPINEFunctionInfo[] all = [");
            builder.AppendLine();

            for (var i = 0; i < Model.Functions.Count; i++)
            {

                var function = Model.Functions[i];

                builder.AppendLine($"            new (\"{function.Name}\",");
                builder.AppendLine($"                 \"{function.Resource}\",");
                builder.AppendLine($"                 typeof({function.DataType}),");
                builder.AppendLine($"                 {(function.SelectorsType is null ? "null" : $"typeof({function.SelectorsType})")},");
                builder.AppendLine($"                 {(function.ElementsType  is null ? "null" : $"typeof({function.ElementsType})")}){(i < Model.Functions.Count - 1 ? "," : "")}");
                builder.AppendLine();

            }

            builder.AppendLine( "        ];");
            builder.AppendLine();
            builder.AppendLine( "        private static readonly Dictionary<String, SPINEFunctionInfo> lookup =");
            builder.AppendLine( "            all.ToDictionary(function => function.Name, StringComparer.Ordinal);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region Properties");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// All functions of the SPINE data model.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        public static IEnumerable<SPINEFunctionInfo> All");
            builder.AppendLine( "            => all;");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine( "        #region TryGet(Name, out Function)");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// Try to find the function of the given name.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Name\">A function name.</param>");
            builder.AppendLine( "        /// <param name=\"Function\">The function.</param>");
            builder.AppendLine( "        public static Boolean TryGet(String Name, out SPINEFunctionInfo? Function)");
            builder.AppendLine();
            builder.AppendLine( "            => lookup.TryGetValue(Name, out Function);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "        #region Get   (Name)");
            builder.AppendLine();
            builder.AppendLine( "        /// <summary>");
            builder.AppendLine( "        /// The function of the given name, or null.");
            builder.AppendLine( "        /// </summary>");
            builder.AppendLine( "        /// <param name=\"Name\">A function name.</param>");
            builder.AppendLine( "        public static SPINEFunctionInfo? Get(String Name)");
            builder.AppendLine();
            builder.AppendLine( "            => lookup.GetValueOrDefault(Name);");
            builder.AppendLine();
            builder.AppendLine( "        #endregion");
            builder.AppendLine();
            builder.AppendLine( "    }");
            builder.AppendLine();
            builder.AppendLine( "}");

            Write(Path.Combine(OutputDirectory, "SPINEFunctions.cs"), builder);

        }

        #endregion


        #region (private) Header(What, Usings) / Write(Path, Builder)

        private StringBuilder Header(String What, String[] Usings)
        {

            var builder = new StringBuilder();

            builder.AppendLine("/*");
            builder.AppendLine(" * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>");
            builder.AppendLine(" * This file is part of WWCP EEBUS <https://github.com/OpenChargingCloud/WWCP_EEBUS>");
            builder.AppendLine(" *");
            builder.AppendLine(" * Licensed under the Apache License, Version 2.0 (the \"License\");");
            builder.AppendLine(" * you may not use this file except in compliance with the License.");
            builder.AppendLine(" * You may obtain a copy of the License at");
            builder.AppendLine(" *");
            builder.AppendLine(" *     http://www.apache.org/licenses/LICENSE-2.0");
            builder.AppendLine(" *");
            builder.AppendLine(" * Unless required by applicable law or agreed to in writing, software");
            builder.AppendLine(" * distributed under the License is distributed on an \"AS IS\" BASIS,");
            builder.AppendLine(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.");
            builder.AppendLine(" * See the License for the specific language governing permissions and");
            builder.AppendLine(" * limitations under the License.");
            builder.AppendLine(" */");
            builder.AppendLine();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine($"//     {What}.");
            builder.AppendLine("//");
            builder.AppendLine($"//     Generated from the official SPINE {Model.Version} XSDs by Apps/EEBUSModelGen.");
            builder.AppendLine("//     Every change made here is lost the next time the generator runs.");
            builder.AppendLine("//");
            builder.AppendLine("//     Where the XSD cannot express what is needed, the answer belongs into the");
            builder.AppendLine("//     generator, into a hand-written type below WWCP_EEBUS_SPINE/DataStructures/,");
            builder.AppendLine("//     or - for behaviour of a generated type - into its partial class below");
            builder.AppendLine("//     WWCP_EEBUS_SPINE/Additions/.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();

            if (Usings.Length > 0)
            {

                builder.AppendLine("#region Usings");
                builder.AppendLine();

                foreach (var @using in Usings)
                    builder.AppendLine($"using {@using};");

                builder.AppendLine();
                builder.AppendLine("#endregion");
                builder.AppendLine();

            }

            // The "<auto-generated>" marker above makes the compiler treat this
            // file as generated code, and generated code has to state its
            // nullable context itself (CS8669).
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine($"namespace {Namespace}");
            builder.AppendLine("{");

            return builder;

        }


        private void Write(String Path, StringBuilder Builder)

            => Write(Path, Builder.ToString());


        private void Write(String Path, String Text)
        {

            File.WriteAllText(Path, Text.ReplaceLineEndings("\r\n"));

            writtenFiles.Add(Path);

        }

        #endregion

    }

}
