<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>cloud.charging.open.protocols.EEBus.Conformance.tests</RootNamespace>
    <AssemblyName>cloud.charging.open.protocols.EEBus.Conformance.tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libs\WWCP_EEBus\WWCP_EEBus_SHIP\WWCP_EEBus_SHIP.csproj" />
    <ProjectReference Include="..\..\libs\WWCP_EEBus\WWCP_EEBus_SPINE\WWCP_EEBus_SPINE.csproj" />
    <ProjectReference Include="..\..\libs\WWCP_EEBus\WWCP_EEBus_UseCases\WWCP_EEBus_UseCases.csproj" />
  </ItemGroup>

</Project>
